### ISSUE TITLE
Enable Metrics

### ISSUE THREAD

**Issue by chrisvrose** [IEEE-RVCE/reforseti#15]
Metrics should not be too difficult to get, since `spring-boot-starter-actuator` is already a dependency.

### Importance

Metrics give you data to drive a decision. Eg. by looking at requests per second and response time, we can understand if we need to scale up/down our server.

### Tasklist
- Get the actuator endpoint for metrics enabled
- Add some reasonable metrics:
  - Response time
  - Number of requests

**Comment by Prajwalprakash3722** [comment]
I shall take this up, as I have dabbled in this area in past.

**Comment by chrisvrose** [comment]
Please take up metrics integration, I've completed integration
