### ISSUE TITLE
DeLombok

### ISSUE THREAD

**Issue by chrisvrose** [IEEE-RVCE/reforseti#30]
Lombok is good, but confusing for new devs. Will be removing it for easier understanding for newer people

**Comment by chrisvrose** [comment]
Also removes some compile time strain

**Comment by Prajwalprakash3722** [comment]
I mean this will make stuff easier

**Comment by chrisvrose** [comment]
Looked through all the code, for some cases it is really useful. Eg. `@Data` and `@HashCode`.
Keeping it for now.
